name: SonarCloud Scanner

on:
  push:
    branches:
    - master

jobs:
  scan:

    name: Code Scanner
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2.3.4
    - name: Set up Java 11
      uses: actions/setup-java@v2.1.0
      with:
        java-version: '11'
        distribution: 'adopt'
        java-package: jdk
        architecture: x64
    - name: SonarCloud Scan
      run: mvn compile sonar:sonar -Dsonar.login=${{ secrets.SONARCLOUD_TOKEN }} -Dsonar.host.url=https://sonarcloud.io -Dsonar.projectKey=TheBusyBiscuit_CS-CoreLib2 -Dsonar.organization=thebusybiscuit-github
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
